### PR TITLE
Add io errors check

### PR DESCRIPTION
**Pull request by blkperl**
## Output
```
{noformat:title=io_error                       on ded-11716.prod.hosting.acquia.com                  fail}
    ...812.982348] lost page write due to I/O error on xvda1
    Dec 10 22:07:27 $host kernel: [102305812.982352] Buffer I/O error on device xvda1, logical block 32407
    Dec 10 22:07:27 $host kernel: [102305812.982358] lost page write due to I/O error on xvda1
{noformat}
```

### CODE REVIEW

**Comment by pdrakeweb** [comment]
Does this happen while servers are running or just at boot (resulting in a read-only mount)?

**Comment by blkperl** [comment]
@pdrakeweb while they are running.

**Comment by tnorris** [comment]
Looks good to me @blkperl

**Comment by tnorris** [comment]
Maybe `tail -n 5000` or similar, in case you end up on a server with a ridiculously huge kern log? (I don't think I have seen this in practice, though)

**Pull request merged**
